// topActions.js
export const START_REQUEST = 'START_REQUEST';
export const LOAD_STORIES_SUCCESS = 'LOAD_STORIES_SUCCESS';

// newActions.js
export const NEW_STORIES_SUCCESS = 'NEW_STORIES_SUCCESS';


// itemActions.js
export const FETCH_SPECIFIC_STORY_SUCCESS = 'FETCH_SPECIFIC_STORY_SUCCESS';


export const FETCH_SPECIFIC_COMMENT_LIST = 'FETCH_SPECIFIC_COMMENT_LIST';
export const SET_NUM_INDENT = 'SET_NUM_INDENT';
export const TOGGLE_EXPAND = 'TOGGLE_EXPAND';